TrevisanLucaProvaSituazionale/Models/CinemaViewModel.cs
using TrevisanLucaProvaSituazionale.Domain;

namespace TrevisanLucaProvaSituazionale.Models;

public record CinemaViewModel(Cinema Cinema, decimal Gross);

TrevisanLucaProvaSituazionale/Controllers/CinemaHallsController.cs
#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrevisanLucaProvaSituazionale.Data;
using TrevisanLucaProvaSituazionale.Models;

namespace TrevisanLucaProvaSituazionale.Controllers
{
    public class CinemaHallsController : Controller
    {
        private readonly ProgettoCinemaDbContext _context;

        public CinemaHallsController(ProgettoCinemaDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? id)
        {
            if (id is null)
            {
                var cinemas = await _context.CinemaHalls
                    .Include(ch => ch.Film)
                    .Include(ch => ch.Tickets)
                    .Include(ch => ch.Spectators)
                    .ToListAsync();

                var result = cinemas.Select(c => new CinemaHallIndexViewModel(c, c.CalculateGross(), c.Spectators.Count()));
                return View(result);
            }
            else
            {
                var cinemas = await _context.CinemaHalls
                       .Include(ch => ch.Film)
                       .Include(ch => ch.Tickets)
                       .Include(ch => ch.Spectators)
                       .ToListAsync();
                var result = cinemas.Select(c => new CinemaHallIndexViewModel(c, c.CalculateGross(), c.Spectators.Count()));
                return View(result);
            }
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
                return NotFound();

            var cinemaHall = await _context.CinemaHalls
                .Include(ch => ch.Cinema)
                .Include(ch => ch.Film)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (cinemaHall is null)
                return NotFound();

            return View(cinemaHall);
        }

        public async Task<IActionResult> Create()
        {
            var cinemas = await _context.Cinemas.ToListAsync();
            var movies = await _context.Films.ToListAsync();
            var viewModel = new CinemaHallViewModel(cinemas, null, movies);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CinemaHallViewModel cinemaHallViewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cinemaHallViewModel.CinemaHall);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cinemaHallViewModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
                return NotFound();

            var cinemaHall = await _context.CinemaHalls.FindAsync(id);
            if (cinemaHall is null)
                return NotFound();

            var cinemas = await _context.Cinemas.ToListAsync();
            var movies = await _context.Films.ToListAsync();
            var viewModel = new CinemaHallViewModel(cinemas, cinemaHall, movies);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CinemaHallViewModel cinemaHallViewModel)
        {
            if (id != cinemaHallViewModel.CinemaHall.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cinemaHallViewModel.CinemaHall);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CinemaHallExists(cinemaHallViewModel.CinemaHall.Id))
                        return NotFound();
                    else
                        throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cinemaHallViewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
                return NotFound();

            var cinemaHall = await _context.CinemaHalls
                .FirstOrDefaultAsync(m => m.Id == id);

            if (cinemaHall is null)
                return NotFound();

            return View(cinemaHall);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cinemaHall = await _context.CinemaHalls.FindAsync(id);
            _context.CinemaHalls.Remove(cinemaHall);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> EmptyHall(int id)
        {
            var cinemaHall = await _context.CinemaHalls
                .Include(ch => ch.Spectators)
                .FirstOrDefaultAsync(ch => ch.Id == id);

            if (cinemaHall is not null)
            {
                foreach (var spectator in cinemaHall.Spectators)
                    spectator.CinemaHallId = null;

                _context.Spectators.UpdateRange(cinemaHall.Spectators);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }
        private bool CinemaHallExists(int id) =>
            _context.CinemaHalls.Any(e => e.Id == id);
    }
}

TrevisanLucaProvaSituazionale/Controllers/CinemasController.cs
#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrevisanLucaProvaSituazionale.Data;
using TrevisanLucaProvaSituazionale.Domain;
using TrevisanLucaProvaSituazionale.Models;

namespace TrevisanLucaProvaSituazionale.Controllers
{
    public class CinemasController : Controller
    {
        private readonly ProgettoCinemaDbContext _context;

        public CinemasController(ProgettoCinemaDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var cinemas = await _context.Cinemas
                .Include(c=>c.CinemaHalls)
                .ThenInclude(ch => ch.Tickets)
                .ToListAsync();

            var viewModel = cinemas.Select(c => new CinemaViewModel(c, c.CalculateGross()));
            return View(viewModel);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)            
                return NotFound();
            

            var cinema = await _context.Cinemas
                .FirstOrDefaultAsync(m => m.Id == id);

            if (cinema is null)            
                return NotFound();            

            return View(cinema);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Cinema cinema)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cinema);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cinema);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)            
                return NotFound();            

            var cinema = await _context.Cinemas.FindAsync(id);
            
            if (cinema is null)            
                return NotFound();
            
            return View(cinema);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Cinema cinema)
        {
            if (id != cinema.Id)            
               return NotFound();
            

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cinema);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CinemaExists(cinema.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cinema);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)            
               return NotFound();            

            var cinema = await _context.Cinemas
                .FirstOrDefaultAsync(m => m.Id == id);

            if (cinema is null)            
                return NotFound();            

            return View(cinema);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cinema = await _context.Cinemas.FindAsync(id);
            _context.Cinemas.Remove(cinema);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CinemaExists(int id)
        {
            return _context.Cinemas.Any(e => e.Id == id);
        }
    }
}

TrevisanLucaProvaSituazionale/Views/Cinemas/Create.cshtml
@model Cinema

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cinema</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back to List","Index",null,null, new { @class = "btn btn-sm btn-primary" })
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

TrevisanLucaProvaSituazionale/Views/Cinemas/Delete.cshtml
@model Cinema

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cinema</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        @Html.ActionLink("Back to List", "Index",null,null, new { @class = "btn btn-sm btn-primary" })
    </form>
</div>

TrevisanLucaProvaSituazionale/Views/Cinemas/Details.cshtml
@model Cinema

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cinema</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit","Edit",null,new {Id = Model?.Id}, new { @class = "btn btn-sm btn-outline-primary" })
    @Html.ActionLink("Back to List","Index",null,null, new { @class = "btn btn-sm btn-primary" })
</div>

TrevisanLucaProvaSituazionale/Views/Cinemas/Edit.cshtml
@model Cinema

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cinema</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Back to List","Index", null, null, new { @class = "btn btn-sm btn-outline-primary" })
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

TrevisanLucaProvaSituazionale/Views/Cinemas/Index.cshtml
@model IEnumerable<CinemaViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cinema.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gross)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Cinema.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gross)
                </td>
                <td>
                    @Html.ActionLink("View cinema's halls","Index","CinemaHalls",new {Id = item.Cinema.Id}, new { @class = "btn btn-sm btn-outline-primary" })
                    @Html.ActionLink("Edit","Edit", new {Id = item.Cinema.Id}, new { @class = "btn btn-sm btn-outline-primary" })
                    @Html.ActionLink("Details","Details", new {Id = item.Cinema.Id}, new { @class = "btn btn-sm btn-outline-primary" })
                    @Html.ActionLink("Delete","Delete", new {Id = item.Cinema.Id}, new { @class = "btn btn-sm btn-outline-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>